{% set name = "dvc-oss" %}
{% set version = "2.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69d11ea7a69936ec7bc6017242d5c4b8331b3493d2a94b10ffbdecdd598ad876

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - dvc
    - ossfs >=2021.8.0

test:
  imports:
    - dvc_oss
  requires:
    - git
    - pip
  commands:
    - pip check
    - dvc version
    - dvc version | grep oss

about:
  home: https://github.com/iterative/dvc-oss
  summary: Alibaba OSS plugin for DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - shcheklein
