{% set name = "dvc-oss" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1047f734022fcd2b96d32b06bf6e0921cd0a65810f7fc1e9b0fac29a147b6a9a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >={{ python_min }}
    - dvc
    - ossfs >=2023.12.0

test:
  imports:
    - dvc_oss
  requires:
    - git
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - dvc version
    - dvc version | grep oss

about:
  home: https://github.com/iterative/dvc-oss
  summary: Alibaba OSS plugin for DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - shcheklein
